@startuml
left to right direction


actor "Gestore" as Gestore
rectangle "Sistema Gestione Collezione Film"{
    usecase "Scegliere la modalità di upload" as Mod

    usecase "Caricare una libreria in .txt da disco rigido" as UpLib
    usecase "Caricare una libreria da DB" as UpDB

    usecase "Scegliere la modalità di upload" as Mod
    usecase "Nagivare e cercare il file" as File
    usecase "Connettersi al DB" as Connection
}

Gestore --> Mod 

Mod --> UpLib
Mod --> UpDB
UpLib ..> File : <<include>>
UpDB ..> Connection : <<include>>

@enduml